//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [Display(Name = "Mã CTDHg ")]
        public int MaCTDH { get; set; }
        [Display(Name = "Mã đơn hàng ")]
        public Nullable<int> MaDonHang { get; set; }
        [Display(Name = "Tên sản phẩm ")]
        public Nullable<int> MaSP { get; set; }
        [Display(Name = "Số lượng ")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Đơn giá ")]
        public Nullable<decimal> DonGia { get; set; }

        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
