//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [Display(Name = "Mã khách hàng ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public int MaKH { get; set; }
        [Display(Name = "Họ và tên ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string HoTen { get; set; }
        [Display(Name = "Tài khoản ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "{0} chỉ được chứa ký tự và số.")]
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật khẩu ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string MatKhau { get; set; }
        [Display(Name = "Email ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [RegularExpression(@"^.+@gmail\.com$", ErrorMessage = "Email phải có định dạng '@gmail.com'.")]
        public string Email { get; set; }
        [Display(Name = "Địa chỉ ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string DiaChi { get; set; }
        [Display(Name = "Điện thoại ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Số điện thoại phải có 10 chữ số.")]
        public string DienThoai { get; set; }
        [Display(Name = "Giới tính ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày sinh ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
