//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
        [Display(Name = "Mã sản phẩm")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public int MaSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string TenSP { get; set; }
        [Display(Name = "Giá bán")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Giá bán phải là số và có tối đa 2 chữ số thập phân.")]
        [Range(0, Double.MaxValue, ErrorMessage = "Giá bán không hợp lệ.")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string MoTa { get; set; }
        [Display(Name = "Ảnh")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string Anh { get; set; }
        [Display(Name = "Ảnh 1")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string Anh1 { get; set; }
        [Display(Name = "Ảnh 2")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string Anh2 { get; set; }
        [Display(Name = "Ảnh 3 ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string Anh3 { get; set; }
        [Display(Name = "Ảnh 4 ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        public string Anh4 { get; set; }
        [Display(Name = "Ngày cập nhật ")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Số lượng tồn ")]
        [Required(ErrorMessage = "{0} Không được để trống !")]
        [Range(0, int.MaxValue, ErrorMessage = "Giá trị số lượng tồn phải là số nguyên dương.")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Hãng ")]
        public Nullable<int> MaLoaiSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
